import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MantineWrapper from "@/components/MantineWrapper";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "@/contexts/authContext";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-gray-50 text-gray-900">
        <AuthProvider>
          <MantineWrapper>
            <div className="flex">
              {/* Fixed sidebar */}
              <div className="fixed left-0 top-0 h-screen w-20 z-50">
                <Sidebar />
              </div>

              {/* Main content with left padding */}
              <main className="ml-20 w-full min-h-screen overflow-x-hidden">
                {children}
              </main>
            </div>
          </MantineWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
